### ISSUE TITLE
typegen implement default value for fields which have a literal type

### ISSUE THREAD

**Issue by luwqz1** [timoniq/telegrinder#159]

**Comment by vffuunnyy** [comment]
```python
chat_menu_button = MenuButtonWebApp(
    text="Open me 🐍",
    web_app=WebAppInfo(url=HOST),
)
```

```bash
vfny@archlinux ~/c/r/t/e/example_bot (main)> uv run bot/app.py
Traceback (most recent call last):
  File "/..../example_bot/bot/app.py", line 11, in <module>
    from bot.dispatchers import user
  File "/..../example_bot/bot/dispatchers/user.py", line 24, in <module>
    chat_menu_button = MenuButtonWebApp(
                       ^^^^^^^^^^^^^^^^^
TypeError: Missing required argument 'type'
vfny@archlinux ~/c/r/t/e/example_bot (main) [1]> 
```
